### PR TITLE
Fix DXT1 lookup in transparency mode

### LINKED ISSUE #567: Improve quality of generated texture image
Currently when dumping texture when parsing map, we are generating it at [mipmap 16 resolution](https://github.com/beyond-all-reason/maps-metadata/blob/4a84450ce011bbc859fcbce1d3fda597d87fce6e/cloud/map-parser/src/index.ts#L122), the max is 32. Already at mipmap 16, the example map image resolution is 7168x7168 but maybe there are usages that would benefit from even higher full texture dump.

The core problem is that generated mipmap has weird artifacts as noticed by Ice 

Image

the source of artifacts is unknown:
- should we export 32 and then downscale?
- is map parser that uses the mipmap export doing it correctly?
- is there some other bugs in e.g. decompressing?

Ultimately, it needs to be debugged at which level we have degradation and fix it.

### PR DESCRIPTION
**Pull request by burnhamrobertp**
Original PR: https://github.com/beyond-all-reason/map-parser/pull/30

Fixes https://github.com/beyond-all-reason/maps-metadata/issues/567

When processing the DXT1 lookup on each block, there is a bug in color ordering, causing them to be swapped. This caused the 2-bit pixel indices to map to wrong colors, resulting in visible artifacts. Fixes a bug in ParseMapInfoFields when processing certain types of fields inside a TableField. Fixed a bug in applyWater where rgbColor was being used where rgbModifier was intended. Simplifies color math and slight changes to improve readability in parseDxt.

Will not require any changes in maps-metadata besides a version update.

#### Conflicts:
* src/map-parser.ts
* src/parse-dxt.ts

### CODE REVIEW

File: src/map-parser.ts [hunk 1]
```diff
@@ -368,11 +529,26 @@ export class MapParser {
...
-            width: mipmapSize * mapWidthUnits * 32,
-            height: mipmapSize * mapHeightUnits * 32
-        }).background(0x000000);
+        const finalWidth = mipmapSize * mapWidthUnits * 32;
+        const finalHeight = mipmapSize * mapHeightUnits * 32;
+        const finalExpectedLen = finalWidth * finalHeight * 4;
+        const finalBuffer = Buffer.concat(tileStrips);
+
+
+        // Ensure we have a Buffer instance (defensive) before passing to Jimp
```
Comment (p2004a) [inline src/map-parser.ts]: What's the point? `finalBuffer` is created just 2 lines above.

File: src/map-parser.ts [hunk 2]
```diff
@@ -368,11 +529,26 @@ export class MapParser {
...
+        const safeBuffer = Buffer.isBuffer(finalBuffer) ? finalBuffer : Buffer.from(finalBuffer || []);
+
+        try {
+            if (safeBuffer.length !== finalExpectedLen) {
```
Comment (p2004a) [inline src/map-parser.ts]: and then here we use emtpy buffer, isn't it the point of using `tileStrips` and apply background? If we don't have correct tileStrips, shoudln't this throw?

File: src/map-parser.ts [hunk 3]
```diff
@@ -267,36 +270,60 @@ export class MapParser {
...
+
+        let typeMap: Jimp;
+        try {
+            typeMap = new Jimp({ data: tmBuf, width: mapWidth / 2, height: mapHeight / 2 });
+        } catch (err) {
+            const empty = Buffer.alloc((mapWidth / 2) * (mapHeight / 2) * 4, 0);
+            typeMap = new Jimp({ data: empty, width: mapWidth / 2, height: mapHeight / 2 });
+        }
+
+        // Calculate miniMap size from surrounding indices instead of hardcoding
```
Comment (p2004a) [inline src/map-parser.ts]: That's expected by engine https://github.com/beyond-all-reason/RecoilEngine/blob/506700f61701567b9fcd34805c1b37d3dfa22f60/rts/Map/SMF/SMFFormat.h#L34C25-L34C37

File: src/map-parser.ts [hunk 4]
```diff
@@ -267,36 +270,60 @@ export class MapParser {
...
-            width: mapWidth / 2,
-            height: mapHeight / 2
-        });
+        const tmBuf = singleChannelToQuadChannel(typeMapBuffer);
+
+        let typeMap: Jimp;
+        try {
+            typeMap = new Jimp({ data: tmBuf, width: mapWidth / 2, height: mapHeight / 2 });
+        } catch (err) {
+            const empty = Buffer.alloc((mapWidth / 2) * (mapHeight / 2) * 4, 0);
```
Comment (p2004a) [inline src/map-parser.ts]: Why we don't want to throw on bad data but replace it with inavalid data?

**Review by p2004a — COMMENTED** [review]
> parse-dxt.ts:getComponentsFromRGB565 - duplicates a small portion of the python implementation (which was generated using an unknown model) for implementing a color bitshift. This different approach produces smoother color gradienting

The comments there are nonsense. The only thing that changes is that instead of returning color as 0-1 float, we return 0-255 byte. Sure maybe not going via floats has some benefit, but the comment doesn't make sense.

Overall, please delete all AI slop comments that don't add any value and reference previous version of code. The code needs to be commented as is, the commit/pr describes what changed.

The PR also contains a set of unrelated changes/fixes not covered in description. It's hard to review parts of it because of that.

There is also consistent pattern of replacing bad data with incorrect data that I don't get. Bad maps aren't supposed to parse and that's expected.

**Comment by burnhamrobertp** [comment]
Removed all error-handling and fallback code, removed unnecessary changes and comments

**Review by p2004a — COMMENTED** [review]
The sigint change was good, you could just document it pr description.

Overall please cleanup PR description.

File: src/parse-dxt.ts [hunk 5]
```diff
@@ -89,61 +90,63 @@ function generateDXT1Lookup(colorValue0: number, colorValue1: number, out = null
...
 }
 
 
 function getComponentsFromRGB565(color: number) {
-    return {
-        R: ((color & 0b11111000_00000000) >> 8) / 0xff,
-        G: ((color & 0b00000111_11100000) >> 3) / 0xff,
-        B: ((color & 0b00000000_00011111) << 3) / 0xff
-    };
+    // Simple bit shift approach matching Python implementation
```
Comment (p2004a) [inline src/parse-dxt.ts]: This comment is still bad, the previous usage of `0b` was alo cleaner and more readable. Just drop conversion to float.

**Comment by burnhamrobertp** [comment]
PR description has been updated, requested changes made

File: src/map-parser.ts [hunk 6]
```diff
@@ -413,10 +415,13 @@ export class MapParser {
             } else if (field.type === "TableKey") {
                 if (field.value.type === "StringLiteral" || field.value.type === "NumericLiteral" || field.value.type === "BooleanLiteral") {
                     if (field.key.type === "NumericLiteral") {
-                        arr[field.key.type] = field.value.value;
+                        // use the numeric literal value as the array index (was using .type previously which is incorrect)
```
Comment (p2004a) [inline src/map-parser.ts]: Please drop "(was using .type previously which is incorrect)", and we can merge

**Review by p2004a — APPROVED** [review]
Thank you!
